CrwOwnerAddress=""
CrownRPCAddr="127.0.0.1"   
CrownRPCPort=9341     
RpcUser=""         
RpcPass=""        
WalletUnlockPass=""
ProtocolID="testperiod" 
ProtocolDescription="Periodically reg test"
ProtocolSignCode=1
ClientTimeout=1000
TokensToMintInRound=500
MintEvery=3600



